name: PrismoDNS
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 0.1.6
    CURRENT_PROJECT_VERSION: 7
packages:
  PrismoApple:
    path: .
targets:
  PrismoDNS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources/PrismoApp
    info:
      path: Sources/PrismoApp/Info.plist
      properties:
        CFBundleDisplayName: Prismo DNS
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIBackgroundModes:
          - audio
        CFBundleURLTypes:
          - CFBundleURLName: org.prismovpn.dns.deeplink
            CFBundleURLSchemes:
              - prismodns
              - prismo
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: PrismoApple
        product: PrismoKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.prismovpn.dns.ios
        PRODUCT_NAME: Prismo DNS
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
schemes:
  PrismoDNS:
    build:
      targets:
        PrismoDNS: all
    run:
      config: Debug
    archive:
      config: Release
